title: "Сад Трансцендентного Разума"
description: "Диалог с Садоводом - хранителем архива Трансцендентного Рационализма"
theme: jekyll-theme-cayman
show_downloads: false
github:
  is_project_page: true
